AtikVar/Controllers/AboutController.cs
using AtikVar.Sınıf;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AtikVar.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            return View();
        }
    }
}

AtikVar/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AtikVar.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

AtikVar/Controllers/LoginController.cs
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AtikVar.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index(string kullaniciAdi, string sifre)
        {
            HttpClient client = new HttpClient();
            var values = new Dictionary<string, string>
            {
                { "kullaniciAdi", kullaniciAdi },
                { "sifre", sifre },
            };
            var content = new FormUrlEncodedContent(values);
            var response = await client.PostAsync("http://localhost:3003/login", content);
            var responseString = await response.Content.ReadAsStringAsync();
            var parsed = JObject.Parse(responseString);
            if ((int)parsed["durumKodu"] == 200)
            {
                Session["userId"] = (int) parsed["userId"];
                Session["userName"] = parsed["kurumAdi"];
                Session["role"] = parsed["role"];
                return Redirect("/");
            }
            else
                ViewBag.message = parsed["mesaj"].ToString();
            return View();
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return Redirect("/");
        }
    }
}

AtikVar/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json.Linq;

namespace AtikVar.Controllers
{
    public class RegisterController : Controller
    {
        // GET: Register
        public ActionResult Index()
        {
            if (Session["userId"] != null)
                return Redirect("Home");
            return View();
        }

        // POST: Register
        [HttpPost]
        public async Task<ActionResult> Index(string kurumAdi, string kullaniciAdi, string sifre, string adresAdi, string il, string ilce, string adres)
        {
            HttpClient client = new HttpClient();
            var values = new Dictionary<string, string>
            {
                { "kurumAdi", kurumAdi },
                { "kullaniciAdi", kullaniciAdi },
                { "sifre", sifre },
                { "adresAdi", adresAdi },
                { "il", il },
                { "ilce", ilce },
                { "adres", adres },
            };
            var content = new FormUrlEncodedContent(values);
            var response = await client.PostAsync("http://localhost:3003/user", content);
            var responseString = await response.Content.ReadAsStringAsync();
            var parsed = JObject.Parse(responseString);
            ViewBag.message = parsed["mesaj"].ToString();
            return View();
        }
    }
}

AtikVar/Controllers/WasteController.cs
using AtikVar.Sınıf;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AtikVar.Controllers
{
    [LoginControl]
    public class WasteController : Controller
    {
        // GET: Waste
        public async Task<ActionResult> Index()
        {
            if (Session["role"].ToString() == "2")
            {
                try
                {
                    string url = "http://localhost:3003/waste?kullaniciId=" + Session["userId"];
                    HttpClient client = new HttpClient();
                    var response = await client.GetAsync(url);
                    var responseString = await response.Content.ReadAsStringAsync();
                    var parsed = JObject.Parse(responseString);
                    if ((int)parsed["durumKodu"] == 200)
                    {
                        ViewBag.waste = parsed["rows"];
                    }
                    else
                        ViewBag.message = parsed["mesaj"].ToString();
                }
                catch (HttpRequestException e)
                {
                    Console.WriteLine(e.ToString());
                }
                return View();
            }
            else if(Session["role"].ToString()=="1")
            {
                try
                {
                    string url = "http://localhost:3003/allWaste";
                    HttpClient client = new HttpClient();
                    var response = await client.GetAsync(url);
                    var responseString = await response.Content.ReadAsStringAsync();
                    var parsed = JObject.Parse(responseString);
                    if ((int)parsed["durumKodu"] == 200)
                    {
                        ViewBag.waste = parsed["rows"];
                    }
                    else
                        ViewBag.message = parsed["mesaj"].ToString();
                }
                catch (HttpRequestException e)
                {
                    Console.WriteLine(e.ToString());
                }
                return View("AllWastes");
            }
            return View();
        }

        public async Task<ActionResult> Add()
        {
            try
            {
                HttpClient client = new HttpClient();
                var response = await client.GetAsync("http://localhost:3003/wasteType");
                var responseString = await response.Content.ReadAsStringAsync();
                var parsed = JObject.Parse(responseString);
                if ((int)parsed["durumKodu"] == 200)
                {
                    ViewBag.wasteTypes = parsed["rows"];
                }
                else
                    ViewBag.message = parsed["mesaj"].ToString();
            }
            catch (HttpRequestException e)
            {
                Console.WriteLine(e.ToString());
            }
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Add(string atikTuru, string miktar, string miktarTip)
        {
            try
            {
                HttpClient client = new HttpClient();
                var values = new Dictionary<string, string>
                {
                    { "atikTuru", atikTuru.ToString() },
                    { "miktar", miktar.ToString()},
                    { "miktarTip", miktarTip },
                    { "kullaniciId", Session["userId"].ToString()}
                };
                var content = new FormUrlEncodedContent(values);
                var response = await client.PostAsync("http://localhost:3003/waste", content);
                var responseString = await response.Content.ReadAsStringAsync();
                var parsed = JObject.Parse(responseString);
                ViewBag.message = parsed["mesaj"].ToString();

                response = await client.GetAsync("http://localhost:3003/wasteType");
                responseString = await response.Content.ReadAsStringAsync();
                parsed = JObject.Parse(responseString);
                if ((int)parsed["durumKodu"] == 200)
                {
                    ViewBag.wasteTypes = parsed["rows"];
                }
                else
                    ViewBag.message = parsed["mesaj"].ToString();
            }
            catch (HttpException e)
            {
                Console.WriteLine(e.ToString());
            }

            return View();
        }
    }
}

AtikVar/Views/About/Index.cshtml
@{
    ViewBag.Title = "Hakkımızda";
}
<div class="row">
    <div class="col-lg-12">
        <div class="jumbotron bg-dark text-white border-success shadow">
            <h1 class="display-4">Hakkında</h1>
            <p class="lead">Atik Var! web uygulaması ile sisteme kayıt olup bünyenizdeki atıkları miktarlarıyla tanımlayıp, uygulamaya kayıt olduğunuz günden itibaren sayenizde gerçekleşen geri dönüşüm ve kazanımları görebelir ve yetkilelerin atıklarınızı almalarını sağlayabilirsiniz.  </p>
        </div>
        <h1 class="lead text-center">Atık Türleri</h1>
        <hr class="my-4">
    </div>
    <div class="col-lg-3 mb-3">
        <div class="card text-dark bg-light">
            <div class="card-header lead"><i class="fa fa-copy text-success"></i> Kağıt Atık</div>
            <div class="card-body" style="min-height: 208px;">
                <p class="card-text">Kağıdın geri dönüşümü ile kullanılan hammadde miktarında önemli oranda tasarruf sağlanması ve ekonomik değerinin yüksek olması nedeniyle önemlidir</p>
            </div>
        </div>
    </div>
    <div class="col-lg-3 mb-3">
        <div class="card text-dark bg-light">
            <div class="card-header lead"><i class="fa fa-shopping-bag text-info"></i> Plastik Atık</div>
            <div class="card-body">
                <p class="card-text">Plastikler, kullanım ömrü sonunda bir kenara atılamayacak kadar değerli bir kaynaktır. Geri dönüştürülerek ilk hallerine geri getirilebilir yahut yeni bir madde oluşturabilirler.</p>
            </div>
        </div>
    </div>
    <div class="col-lg-3 mb-3">
        <div class="card text-dark bg-light">
            <div class="card-header lead"><i class="fa fa-battery-empty text-warning"></i> Atık Pil</div>
            <div class="card-body" style="min-height: 208px;">
                <p class="card-text">Kullanım ömrünü tamamlamış veya uğramış olduğu fiziksel hasar sonucu kullanılmayacak duruma gelmiş pillere “Atık Pil" denir.</p>
            </div>
        </div>
    </div>
    <div class="col-lg-3 mb-3">
        <div class="card text-dark bg-light">
            <div class="card-header lead"><i class="fa fa-wine-bottle text-info"></i> Cam Atık</div>
            <div class="card-body" style="min-height: 208px;">
                <p class="card-text">Camın ana maddesi kumdur. Kum, soda ve kireç. Bu malzemeler, 1500 dereceye kadar ısıtılarak eritilir.</p>
            </div>
        </div>
    </div>
</div>

AtikVar/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Anasayfa";
}
<div class="row">
    <div class="col-lg-12">
        @if (ViewBag.message != null)
        {
            <div class="alert alert-info">
                @ViewBag.message
            </div>
        }
            <div class="jumbotron bg-light shadow">
                @if (Session["userId"] == null)
                {
                    <h1 class="display-4">Yarınları Kurtarmaya Bugünden Başla</h1>
                    <p class="lead">Atik Var! web uygulaması ile sisteme kayıt olup bünyenizdeki atıkları miktarlarıyla tanımlayıp, uygulamaya kayıt olduğunuz günden itibaren sayenizde gerçekleşen geri dönüşüm ve kazanımları görebelir ve yetkilelerin atıklarınızı almalarını sağlayabilirsiniz.</p>
                    <hr class="my-4">
                    <p>Başlamak için önce kayıt olunuz.</p>
                    <a class="btn btn-success btn-lg my-color" href="@Url.Action("Index","Register")" role="button">Kayıt Ol</a>
                }
                else
                {
                    <h1 class="display-4">Hoşgeldin, @Session["userName"]</h1>
                    <hr class="my-4">
                    <p class="lead">
                        Atik Var! web uygulaması ile sisteme kayıt olup bünyenizdeki atıkları miktarlarıyla tanımlayıp, uygulamaya kayıt olduğunuz günden itibaren sayenizde gerçekleşen geri dönüşüm ve kazanımları görebelir ve yetkilelerin atıklarınızı almalarını sağlayabilirsiniz.
                        @if (Session["role"] != null && Session["role"].ToString() == "2")
                        { <a class="mt-3 btn btn-outline-success btn-lg shadow btn-block my-color" href="@Url.Action("Add", "Waste")" role="button"><i class="fa fa-dumpster"></i> ATIK EKLE</a> }
                    </p>
                }
            </div>
        <h1 class="lead text-center">Atık Türleri</h1>
        <hr class="my-4">
    </div>
    <div class="col-lg-3 mb-3">
        <div class="card text-dark bg-light">
            <div class="card-header lead"><i class="fa fa-copy text-success"></i> Kağıt Atık</div>
            <div class="card-body" style="min-height: 208px;">
                <p class="card-text">Kağıdın geri dönüşümü ile kullanılan hammadde miktarında önemli oranda tasarruf sağlanması ve ekonomik değerinin yüksek olması nedeniyle önemlidir</p>
            </div>
        </div>
    </div>
    <div class="col-lg-3 mb-3">
        <div class="card text-dark bg-light">
            <div class="card-header lead"><i class="fa fa-shopping-bag text-info"></i> Plastik Atık</div>
            <div class="card-body">
                <p class="card-text">Plastikler, kullanım ömrü sonunda bir kenara atılamayacak kadar değerli bir kaynaktır. Geri dönüştürülerek ilk hallerine geri getirilebilir yahut yeni bir madde oluşturabilirler.</p>
            </div>
        </div>
    </div>
    <div class="col-lg-3 mb-3">
        <div class="card text-dark bg-light">
            <div class="card-header lead"><i class="fa fa-battery-empty text-warning"></i> Atık Pil</div>
            <div class="card-body" style="min-height: 208px;">
                <p class="card-text">Kullanım ömrünü tamamlamış veya uğramış olduğu fiziksel hasar sonucu kullanılmayacak duruma gelmiş pillere “Atık Pil" denir.</p>
            </div>
        </div>
    </div>
    <div class="col-lg-3 mb-3">
        <div class="card text-dark bg-light">
            <div class="card-header lead"><i class="fa fa-wine-bottle text-info"></i> Cam Atık</div>
            <div class="card-body" style="min-height: 208px;">
                <p class="card-text">Camın ana maddesi kumdur. Kum, soda ve kireç. Bu malzemeler, 1500 dereceye kadar ısıtılarak eritilir.</p>
            </div>
        </div>
    </div>
</div>

AtikVar/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Giriş Yap";
}
<div class="row">
    <div class="col-lg-12">
        <div class="jumbotron bg-light">
            <h1 class="display-4">Giriş Formu</h1>
            <hr class="my-4">
            @if (ViewBag.message != null)
            {
                <div class="alert alert-info">
                    @ViewBag.message
                </div>
            }
            <h4 class="lead my-4">Giriş Bilgileri</h4>
            <form action="@Url.Action("Index","Login")" class="needs-validation" method="post" novalidate>
                <div class="form-group">
                    <label for="kullaniciAdi">Kullanıcı Adı</label>
                    <input type="text" name="kullaniciAdi" class="form-control" id="kullaniciAdi" required>
                    <div class="invalid-feedback">
                        Lütfen kullanıcı adını giriniz
                    </div>
                    <div class="valid-feedback">
                        Tamam
                    </div>
                </div>
                <div class="form-group">
                    <label for="sifre">Password</label>
                    <input type="password" class="form-control" name="sifre" min="8" id="sifre" required>
                    <div class="invalid-feedback">
                        Lütfen minimum 8 karekterli bir şifre giriniz
                    </div>
                    <div class="valid-feedback">
                        Tamam
                    </div>
                </div>
                <button type="submit" class="btn btn-outline-info btn-lg"><i class="fa fa-user"></i> Giriş Yap</button>
            </form>
            <script>
                // Example starter JavaScript for disabling form submissions if there are invalid fields
                (function() {
                  'use strict';
                  window.addEventListener('load', function() {
                    // Fetch all the forms we want to apply custom Bootstrap validation styles to
                    var forms = document.getElementsByClassName('needs-validation');
                    // Loop over them and prevent submission
                    var validation = Array.prototype.filter.call(forms, function(form) {
                      form.addEventListener('submit', function(event) {
                        if (form.checkValidity() === false) {
                          event.preventDefault();
                          event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                      }, false);
                    });
                  }, false);
                })();
            </script>
        </div>
    </div>
</div>

AtikVar/Views/Register/Index.cshtml
@{
    ViewBag.Title = "Kayıt Ol";
}
<div class="row">
    <div class="col-lg-12">
        <div class="jumbotron bg-light">
            <h1 class="display-4">Kayıt Formu</h1>
            <hr class="my-4">
            @if (ViewBag.message != null)
            {
                <div class="alert alert-info">
                    @ViewBag.message
                </div>
            }
            <h4 class="lead my-4">Giriş Bilgileri</h4>
            <form action="@Url.Action("Index","Register")" class="needs-validation" method="post" novalidate>
                <div class="form-group">
                    <label for="kurumAdi">Kurum Adı</label>
                    <input type="text" name="kurumAdi" class="form-control" id="kurumAdi" required>
                    <div class="invalid-feedback">
                        Lütfen bir kurum adı giriniz
                    </div>
                    <div class="valid-feedback">
                        Tamam
                    </div>
                </div>
                <div class="form-group">
                    <label for="kullaniciAdi">Kullanıcı Adı</label>
                    <input type="text" name="kullaniciAdi" class="form-control" id="kullaniciAdi" required>
                    <div class="invalid-feedback">
                        Lütfen kullanıcı adını giriniz
                    </div>
                    <div class="valid-feedback">
                        Tamam
                    </div>
                </div>
                <div class="form-group">
                    <label for="sifre">Password</label>
                    <input type="password" class="form-control" name="sifre" min="8" id="sifre" required>
                    <div class="invalid-feedback">
                        Lütfen minimum 8 karekterli bir şifre giriniz
                    </div>
                    <div class="valid-feedback">
                        Öneri: Şifreniz minimum 8 karekterden oluşmasını öneririz.
                    </div>
                </div>
                <h4 class="lead my-4">Adres Bilgileri</h4>
                <div class="form-group">
                    <label for="adresAdi">Adres Adı</label>
                    <input type="text" name="adresAdi" class="form-control" id="adresAdi" required>
                </div>
                <div class="form-group">
                    <label for="il">İl</label>
                    <select name="il" id="il" class="form-control" required>
                        <option value="">Seçin...</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="ilce">İlçe</label>
                    <select name="ilce" id="ilce" class="form-control" disabled="disabled" required>
                        <option value="">Seçin...</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="tamAdres">Adres</label>
                    <textarea name="adres" class="form-control" id="tamAdres" required></textarea>
                </div>
                <button type="submit" class="btn btn-outline-success btn-lg"><i class="fa fa-recycle"></i> Kayıt Ol</button>
            </form>
            <script>
                // Example starter JavaScript for disabling form submissions if there are invalid fields
                (function() {
                  'use strict';
                  window.addEventListener('load', function() {
                    // Fetch all the forms we want to apply custom Bootstrap validation styles to
                    var forms = document.getElementsByClassName('needs-validation');
                    // Loop over them and prevent submission
                    var validation = Array.prototype.filter.call(forms, function(form) {
                      form.addEventListener('submit', function(event) {
                        if (form.checkValidity() === false) {
                          event.preventDefault();
                          event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                      }, false);
                    });
                  }, false);
                })();
            </script>
        </div>
    </div>
</div>

AtikVar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@ViewBag.Title · Atık Var!</title>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <link rel="icon" type="image/png" sizes="32x32" href="~/images/favicon.png">
    <link href="~/Content/all.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg sticky-top navbar-dark @(Session["role"]!=null && Session["role"].ToString() == "1" ? "bg-dark" : "bg-success")">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")"><img src="~/images/logo.png" width="100"/></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item @(ViewContext.RouteData.Values["Controller"].ToString() == "Home" ? "active" : "")">
                        <a class="nav-link" href="@Url.Action("Index","Home")"><i class="fa fa-home"></i> Anasayfa <span class="sr-only">(Aktif)</span></a>
                    </li>
                    <li class="nav-item @(ViewContext.RouteData.Values["Controller"].ToString() == "Waste" ? "active" : "")">
                        <a class="nav-link" href="@Url.Action("Index","Waste")"><i class="fa fa-recycle"></i> Atıklar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fa fa-chart-pie"></i> İstatistik</a>
                    </li>
                    @if (Session["userId"] == null)
                    {
                        <li class="nav-item @(ViewContext.RouteData.Values["Controller"].ToString() == "Register" ? "active" : "")">
                            <a href="@Url.Action("Index", "Register")" class="nav-link"><i class="fa fa-user-plus"></i> Kayıt Ol</a>
                        </li>
                    }
                    <li class="nav-item @(ViewContext.RouteData.Values["Controller"].ToString() == "About" ? "active" : "")">
                        <a href="@Url.Action("Index","About")" class="nav-link"><i class="fa fa-info-circle"></i> Hakkında</a>
                    </li>
                </ul>
                @if (Session["userId"] == null)
                {
                    <span class="navbar-text"><a href="@Url.Action("Index", "Login")" class="btn text-dark btn-light"><i class="fa fa-user-circle"></i> Giriş Yap</a></span>
                }
                else
                {
                    <span class="navbar-text"><a href="@Url.Action("Logout", "Login")" class="btn text-dark btn-light"><i class="fa fa-sign-out-alt"></i> Çıkış</a></span>
                }
            </div>
        </div>
    </nav>
    <main class="container pt-2">
        @RenderBody()
    </main>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/atikVar.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

AtikVar/Views/Waste/Index.cshtml
@{
    ViewBag.Title = "Atıklarım";
}
<div class="row">
    <div class="col-lg-12">
        <div class="jumbotron bg-light shadow">
            <h1 class="display-4 mb-4">Atıklarım <a class="mt-3 btn btn-outline-success shadow my-color" href="@Url.Action("Add", "Waste")" role="button"><i class="fa fa-dumpster"></i> ATIK EKLE <i class="fa fa-plus fa-1x"></i></a></h1>
            @if (ViewBag.message != null)
            {
                <div class="alert alert-light p-4 shadow border">
                    @ViewBag.message
                </div>
            }
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col"><i class="fa fa-recycle"></i> Atık Türü</th>
                        <th scope="col"><i class="fa fa-equals"></i> Miktar</th>
                        <th scope="col"><i class="fa fa-bullhorn"></i> Durumu</th>
                        <th scope="col"><i class="fa fa-calendar-alt"></i> Tarih</th>  
                    </tr>
                </thead>
                <tbody>
                    @foreach (var waste in ViewBag.waste)
                    {
                        <tr>
                            <td>@waste.cinsi</td>
                            <td>@waste.miktar @waste.miktar_tip</td>
                            <td>@if (waste.bekliyor == 1)
                            {<text><i class="fa fa-spinner fa-1x text-warning"></i> Atığın alınması bekleniyor</text>}
                            else { <text><i class="fa fa-check fa-1x text-success"></i> Dönüşüm Tamamlandı</text> }</td>
                            <td>@waste.ekleme_tarihi</td>
                        </tr>
                    }
                    </tbody>
            </table>
            <script>
                // Example starter JavaScript for disabling form submissions if there are invalid fields
                (function () {
                    'use strict';
                    window.addEventListener('load', function () {
                        // Fetch all the forms we want to apply custom Bootstrap validation styles to
                        var forms = document.getElementsByClassName('needs-validation');
                        // Loop over them and prevent submission
                        var validation = Array.prototype.filter.call(forms, function (form) {
                            form.addEventListener('submit', function (event) {
                                if (form.checkValidity() === false) {
                                    event.preventDefault();
                                    event.stopPropagation();
                                }
                                form.classList.add('was-validated');
                            }, false);
                        });
                    }, false);
                })();
            </script>
        </div>
    </div>
</div>

AtikVar/Views/Waste/add.cshtml
@{
    ViewBag.Title = "Atık Ekle";
}
<div class="row">
    <div class="col-lg-12">
        <div class="jumbotron bg-light shadow">
            <h1 class="display-4">Atık Ekle</h1>
            <hr class="my-4">
            @if (ViewBag.message != null)
            {
                <div class="alert alert-light p-4 shadow border">
                    @ViewBag.message
                </div>
            }
            <h4 class="lead my-4">Atık Ekleme Formu</h4>
            <form action="@Url.Action("Add","Waste")" class="needs-validation" method="post" novalidate>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="atikTur">Atık Türü</label>
                    </div>
                    <select class="custom-select" id="atikTur" name="atikTuru" required>
                        @if (ViewBag.wasteTypes != null)
                        {
                            foreach (var type in ViewBag.wasteTypes)
                            {
                                <option value="@type.id">@type.cinsi</option>
                            }
                        }
                        else
                        {
                            <option value="">Api bağlantı hatası</option>
                        }
                    </select>
                    <div class="invalid-feedback">
                        Lütfen Atık türü seçiniz
                    </div>
                    <div class="valid-feedback">
                        Tamam
                    </div>
                </div>
                <div class="input-group form-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Miktar / Türü</span>
                    </div>
                    <input type="number" aria-label="miktar" name="miktar" class="form-control" required>
                    <select class="custom-select" id="atikTur" name="miktarTip" required>
                        <option value="adet">Adet</option>
                        <option value="gr">Gr</option>
                        <option value="kg">Kg</option>
                        <option value="ton">Ton</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-outline-success btn-lg"><i class="fa fa-save"></i> Atık Ekle</button>
            </form>
            <script>
                // Example starter JavaScript for disabling form submissions if there are invalid fields
                (function () {
                    'use strict';
                    window.addEventListener('load', function () {
                        // Fetch all the forms we want to apply custom Bootstrap validation styles to
                        var forms = document.getElementsByClassName('needs-validation');
                        // Loop over them and prevent submission
                        var validation = Array.prototype.filter.call(forms, function (form) {
                            form.addEventListener('submit', function (event) {
                                if (form.checkValidity() === false) {
                                    event.preventDefault();
                                    event.stopPropagation();
                                }
                                form.classList.add('was-validated');
                            }, false);
                        });
                    }, false);
                })();
            </script>
        </div>
    </div>
</div>